basic.showIcon(IconNames.Pitchfork)
serial.setBaudRate(BaudRate.BaudRate115200)
serial.setRxBufferSize(32)
serial.setTxBufferSize(32)
loops.everyInterval(2000, function () {
    basic.showIcon(IconNames.SmallDiamond)
    serial.writeValue("LX", ModuleWorld_Analog.Light(ModuleWorld_Analog.mwAnalogNum.AP0P1))
    basic.pause(300)
    serial.writeValue("TP", ModuleWorld_Digital.dht11value(ModuleWorld_Digital.DHT11Type.DHT11_temperature_C, ModuleWorld_Digital.mwDigitalNum.P2P3))
    basic.pause(300)
    serial.writeValue("RH", ModuleWorld_Digital.dht11value(ModuleWorld_Digital.DHT11Type.DHT11_humidity, ModuleWorld_Digital.mwDigitalNum.P2P3))
    basic.pause(300)
    serial.writeValue("SW", pins.analogReadPin(AnalogReadWritePin.P10))
    basic.pause(200)
    basic.showIcon(IconNames.Diamond)
})
basic.forever(function () {
    basic.showNumber(pins.analogReadPin(AnalogReadWritePin.P10))
})
